[2025-02-28T10:36:26.526+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T10:36:26.546+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_data_transformation.transform_s3_data manual__2025-02-28T10:36:25.870362+00:00 [queued]>
[2025-02-28T10:36:26.557+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_data_transformation.transform_s3_data manual__2025-02-28T10:36:25.870362+00:00 [queued]>
[2025-02-28T10:36:26.557+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-28T10:36:26.577+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_s3_data> on 2025-02-28 10:36:25.870362+00:00
[2025-02-28T10:36:26.587+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15486) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T10:36:26.590+0000] {standard_task_runner.py:72} INFO - Started process 15487 to run task
[2025-02-28T10:36:26.668+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_data_transformation', 'transform_s3_data', 'manual__2025-02-28T10:36:25.870362+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpgktja6kp']
[2025-02-28T10:36:26.678+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask transform_s3_data
[2025-02-28T10:36:26.745+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T10:36:26.822+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_data_transformation.transform_s3_data manual__2025-02-28T10:36:25.870362+00:00 [running]> on host be61fafefd76
[2025-02-28T10:36:27.036+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_data_transformation' AIRFLOW_CTX_TASK_ID='transform_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T10:36:25.870362+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T10:36:25.870362+00:00'
[2025-02-28T10:36:27.039+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T10:36:33.139+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-28T10:36:33.151+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T10:36:33.152+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=s3_data_transformation, task_id=transform_s3_data, run_id=manual__2025-02-28T10:36:25.870362+00:00, execution_date=20250228T103625, start_date=20250228T103626, end_date=20250228T103633
[2025-02-28T10:36:33.202+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-28T10:36:33.230+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T10:36:33.232+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
