[2025-03-01T15:43:59.247+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T15:43:59.268+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_transformed.run_etl_task manual__2025-03-01T15:43:57.827675+00:00 [queued]>
[2025-03-01T15:43:59.280+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_transformed.run_etl_task manual__2025-03-01T15:43:57.827675+00:00 [queued]>
[2025-03-01T15:43:59.281+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T15:43:59.297+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_etl_task> on 2025-03-01 15:43:57.827675+00:00
[2025-03-01T15:43:59.306+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2854) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T15:43:59.308+0000] {standard_task_runner.py:72} INFO - Started process 2856 to run task
[2025-03-01T15:43:59.306+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_transformed', 'run_etl_task', 'manual__2025-03-01T15:43:57.827675+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/s3_transformation_redshift_dag.py', '--cfg-path', '/tmp/tmpnw87lyy4']
[2025-03-01T15:43:59.309+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask run_etl_task
[2025-03-01T15:43:59.325+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T15:43:59.362+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_redshift_transformed.run_etl_task manual__2025-03-01T15:43:57.827675+00:00 [running]> on host 763fac820cd7
[2025-03-01T15:43:59.444+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_transformed' AIRFLOW_CTX_TASK_ID='run_etl_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T15:43:57.827675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T15:43:57.827675+00:00'
[2025-03-01T15:43:59.444+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T15:44:02.093+0000] {logging_mixin.py:190} INFO - Processed data uploaded to s3://dataingestionjson/processed/2025-02-28/transformed_data.parquet
[2025-03-01T15:44:02.094+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-01T15:44:02.105+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T15:44:02.105+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=s3_to_redshift_transformed, task_id=run_etl_task, run_id=manual__2025-03-01T15:43:57.827675+00:00, execution_date=20250301T154357, start_date=20250301T154359, end_date=20250301T154402
[2025-03-01T15:44:02.154+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-01T15:44:02.173+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T15:44:02.174+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
