[2025-03-02T13:02:50.090+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T13:02:50.113+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T13:02:48.307684+00:00 [queued]>
[2025-03-02T13:02:50.123+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T13:02:48.307684+00:00 [queued]>
[2025-03-02T13:02:50.124+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T13:02:50.139+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_repeat_buyers> on 2025-03-02 13:02:48.307684+00:00
[2025-03-02T13:02:50.147+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16963) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T13:02:50.149+0000] {standard_task_runner.py:72} INFO - Started process 16969 to run task
[2025-03-02T13:02:50.148+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'redshift_to_s3_dag', 'execute_repeat_buyers', 'manual__2025-03-02T13:02:48.307684+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/final_aggregation_dag.py', '--cfg-path', '/tmp/tmp7mq504qv']
[2025-03-02T13:02:50.151+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask execute_repeat_buyers
[2025-03-02T13:02:50.168+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T13:02:50.207+0000] {task_command.py:467} INFO - Running <TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T13:02:48.307684+00:00 [running]> on host 22871c84ed32
[2025-03-02T13:02:50.356+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='redshift_to_s3_dag' AIRFLOW_CTX_TASK_ID='execute_repeat_buyers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T13:02:48.307684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T13:02:48.307684+00:00'
[2025-03-02T13:02:50.359+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T13:02:52.904+0000] {logging_mixin.py:190} INFO - Error executing query repeat_buyers: syntax error at or near "#" in context "purchase_count DESC;
    #", at line 10, column 5
LINE 10:     # 
             ^
[2025-03-02T13:02:52.905+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T13:02:52.922+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T13:02:52.923+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=redshift_to_s3_dag, task_id=execute_repeat_buyers, run_id=manual__2025-03-02T13:02:48.307684+00:00, execution_date=20250302T130248, start_date=20250302T130250, end_date=20250302T130252
[2025-03-02T13:02:52.959+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T13:02:52.994+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-02T13:02:52.996+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
